apply {
    from "$project.rootDir/build_scripts/dependencies.gradle"
    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply plugin: 'androidx.navigation.safeargs.kotlin'
}

android {
    namespace 'kz.avtobys.driverboard'
    compileSdk androidCompileSdkVersion

    defaultConfig {
        applicationId "kz.avtobys.driverboard"
        minSdk androidMinSdkVersion
        targetSdk androidTargetSdkVersion
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
        android.buildFeatures.buildConfig true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.9'
    }
    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    flavorDimensions "default"
    productFlavors {
        alpha {
            dimension "default"
            applicationId "kz.avtobys.driverboard.alpha"
            buildConfigField "String", "app_name", '"Avtobys Driver Board ALPHA"'
            buildConfigField "String", "CLIENT_SECRET", '"Basic Y2xpZW50OnNlY3JldA=="'
            buildConfigField "String", "PASS_SECRET", '"test"'
            buildConfigField "String", "OAUTH_API_BASE_URL", '"https://api.alpha.avtobys.kz"'
            buildConfigField "String", "WEB_VIEW_URL", '"https://driver.alpha.avtobys.kz"'
        }
        beta {
            dimension "default"
            applicationId "kz.avtobys.driverboard.beta"
            buildConfigField "String", "app_name", '"Avtobys Driver Board BETA"'
            buildConfigField "String", "CLIENT_SECRET", '"Basic Y2xpZW50OnNlY3JldA=="'
            buildConfigField "String", "PASS_SECRET", '"test"'
            buildConfigField "String", "OAUTH_API_BASE_URL", '"https://api.beta.avtobys.kz"'
            buildConfigField "String", "WEB_VIEW_URL", '"https://driver.beta.avtobys.kz"'
        }
        prod {
            dimension "default"
            applicationId "kz.avtobys.driverboard"
            buildConfigField "String", "app_name", '"Avtobys Driver Board"'
            buildConfigField "String", "CLIENT_SECRET", '"Basic YmIxeUFtWTpwaGhtMjFFVGpCb1FrbE5KMHExVnhn"'
            buildConfigField "String", "PASS_SECRET", '"pujAJEZ7CBV"'
            buildConfigField "String", "OAUTH_API_BASE_URL", '"https://api.avtobys.kz"'
            buildConfigField "String", "WEB_VIEW_URL", '"https://driver2.avtobys.kz/"'
        }
    }
}

dependencies {

    // Jetpack
    implementation jetpack.legacySupport
    implementation jetpack.lifecycleLiveDataKtx
    implementation jetpack.lifecycleViewModelKtx
    implementation jetpack.lifecycleRuntime
    implementation jetpack.compose.values()
    implementation jetpack.accompanist.values()

    //Kotlin
    implementation kotlin.serialization
    implementation kotlin.coroutinesAndroid

    // Core
    implementation androidXDependencies.appcompat
    implementation androidXDependencies.materialDesign
    implementation androidXDependencies.constraintLayout
    implementation androidXDependencies.lifecycleExt
    implementation androidXDependencies.fragmentKtx
    implementation androidXDependencies.coreKtx
    implementation androidXDependencies.nav_ui
    implementation androidXDependencies.nav_fragment
    implementation androidXDependencies.viewPager2
    implementation androidXDependencies.webkit
    implementation androidXDependencies.securityCrypto

    // Chucker
    debugImplementation chuckerDependencies.chucker
    releaseImplementation chuckerDependencies.chuckerNoOp

    // Koin DI
    implementation koinDependencies.values()

    // Network
    implementation networkDependencies.core
    implementation networkDependencies.gsonConverter
    implementation networkDependencies.gson
    implementation networkDependencies.okHttp
    implementation networkDependencies.okHttpInterceptor

    implementation project(":libraries:common")
    implementation project(':libraries:core')

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
