# This file is a template, and might need editing before it works on your project.
stages:          # List of stages for jobs, and their order of execution
  - test
  - move-task-to-ready
  - build
  - move-task-to-test

variables:
  PROJECT_NAME: "AVTOBYS KOTLIN DRIVER BOARD APP"
  # Disable the Gradle daemon for Continuous Integration servers as correctness
  # is usually a priority over speed in CI environments. Using a fresh
  # runtime for each build is more reliable since the runtime is completely
  # isolated from any previous builds.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  CI_SCRIPT_URL: "https://git-server.innoforce.kz/innopay/innoforce-ci-scripts/raw/v2.3"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Это называется YAML anchor. Ну или gitlab-ci.yml anchor
# Позволяет избежать дублирования настроек, что-то вроде наследования
.branches_template: &branches_template
  before_script:
    - if [[ -n ${BUILD_FROM_COMMIT} ]]; then ENVIRONMENT=BETA; fi
    - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle
    - if [ $[ $RANDOM % 7 ] == 0 ]; then rm -rf "$CI_PROJECT_DIR/.gradle/caches/*" "$CI_PROJECT_DIR/.gradle/wrapper/*" && echo 'Cleaning mvn cache!!!'; fi
    - ENVIRONMENT=$(echo "$CI_COMMIT_REF_NAME" | tr a-z A-Z)
    - if [[ "$ENVIRONMENT" = ALPHA ]]; then ENVIRONMENT=ALPHA; BASE_URL=https://api.alpha.avtobys.kz; fi
    - if [[ "$ENVIRONMENT" = BETA ]]; then ENVIRONMENT=BETA; BASE_URL=https://api.beta.avtobys.kz; fi
    - if [[ -n ${BUILD_FROM_COMMIT} ]]; then ENVIRONMENT=BETA; git reset --hard; git checkout ${BUILD_FROM_COMMIT}; fi ## to build any commit
    - ENVIRONMENT_LOWERCASE=$(echo "$ENVIRONMENT" | tr A-Z a-z)
    - ENVIRONMENT_FIRST_LETTER_UPPER="${ENVIRONMENT_LOWERCASE^}"
    - chmod +x ./gradlew
  only:
    - alpha
    - beta
  tags:
    - android
  allow_failure: false
  

# This job also runs in the test stage.
test:
  <<: *branches_template
  only:
    - /.*/
    - merge_requests
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  when: always
  script:
    - echo "sdk.dir="$ANDROID_HOME > local.properties
    - ./gradlew clean
    - ./gradlew assembleBetaDevDebug
  allow_failure: false
  except:
    - alpha
    - beta
    - prod
  tags:
    - docker
    - android
  image: cirrusci/android-sdk:30
    
test-space-task:
  stage: test
  script:
    - wget -O - "${CI_SCRIPT_URL}/test-space-task.sh" | bash -s ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  when: always
  allow_failure: false
  except:
    - alpha
    - beta
    - prod
  only:
    - merge_requests
  tags:
    - ansible

move-task-to-ready:
  stage: move-task-to-ready
  when: always
  <<: *branches_template
  script:
    - wget -O - "${CI_SCRIPT_URL}/move-task-to-ready.sh" | bash -s IF $CI_COMMIT_REF_NAME
  tags:
    - ansible

build:
  stage: build
  <<: *branches_template
  script:
    - export CLIENT_SECRET='Y2xpZW50OnNlY3JldA=='
    - export PASS_SECRET='test'
    - sed -i "s;CLIENT_SECRET;${CLIENT_SECRET};g" app/build.gradle
    - sed -i "s;PASS_SECRET;${PASS_SECRET};g" app/build.gradle
    - sed -i "s;OAUTH_API_BASE_URL;${OAUTH_API_BASE_URL};g" app/build.gradle
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - echo "sdk.dir="$ANDROID_HOME > local.properties
    - ./gradlew clean
    - ./gradlew assembleBetaRelease
    - /opt/android-sdk-linux/build-tools/30.0.3/apksigner sign --ks keystore/release-keystore.jks --ks-key-alias avtobysmobile --ks-pass env:'KEY_PASS' --key-pass env:'KEY_PASS' --out av-mobile-terminal-${ENVIRONMENT}.apk app/build/outputs/apk/beta/release/app-beta-release-unsigned.apk
  artifacts:
    expire_in: 14 days
    paths:
      - ./*apk
  image: cirrusci/android-sdk:30
  when: manual
  retry: 2

move-task-to-test:
  stage: move-task-to-test
  when: on_success
  <<: *branches_template
  script:
    - wget -O - "${CI_SCRIPT_URL}/move-task-to-test.sh" | bash -s IF $ENVIRONMENT
  tags:
    - ansible

build-prod:
  stage: build
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - echo "sdk.dir="$ANDROID_HOME > local.properties
    - sed -i "s;PASS_SECRET_PROD;${PASS_SECRET_PROD};g" app/build.gradle
    - sed -i "s;CLIENT_SECRET_PROD;${CLIENT_SECRET_PROD};g" app/build.gradle
    - sed -i "s;OAUTH_API_BASE_URL_PROD;${OAUTH_API_BASE_URL_PROD};g" app/build.gradle
    - ./gradlew clean
    - ./gradlew assemblePilotRelease
    - /opt/android-sdk-linux/build-tools/30.0.3/apksigner sign --ks keystore/release-keystore.jks --ks-key-alias avtobysmobile --ks-pass env:'KEY_PASS' --key-pass env:'KEY_PASS' --out av-mobile-terminal-prod-${CI_COMMIT_REF_NAME}.apk app/build/outputs/apk/pilot/release/app-pilot-release-unsigned.apk
  artifacts:
    expire_in: 7 days
    paths:
      - ./*apk
  image: cirrusci/android-sdk:30
  when: manual
  retry: 2
  tags:
    - docker
    - android
  allow_failure: false
  only:
    - tags


