[versions]
androidx-junit = "1.1.5"
espressoCore = "3.5.1"
junit = "4.13.2"
min-sdk-version = "24"
target-sdk-version = "34"
compile-sdk-version = "34"
build-tools-version = "34.0.0"

# Plugins
agp = "8.2.2"
jetbrains_kotlin_version = "1.9.10"
android-library = "8.2.2"

# Libraries
appCompat = "1.6.1"
core-ktx = "1.12.0"
lifecycleVersion = "2.7.0"
nav_version = "2.7.7"
chuckerVersion = "3.5.2"
koinVersion = "3.5.3"
retrofitVersion = "2.9.0"
gsonVersion = "2.10.1"
okHttpVersion = "4.12.0"
coroutines_version = "1.8.0"
serialization_version = "1.6.3"
compose_version = "1.6.2"
compose_theme_version = "1.2.1"
constraintlayout-compose-version = "1.0.1"
paging-version = "3.2.1"
compose_material_version = "1.6.2"
coil_version = "2.5.0"
accompanist_version = "0.32.0"
maps_compose_version = "4.3.3"
gradle = "8.2.2"
kotlinGradlePlugin = "1.9.22"
navigationSafeArgsGradlePlugin = "2.7.7"
material-design = "1.11.0"
constraint-layout = "2.1.4"
fragment-ktx = "1.6.2"
lifecycle-ext = "2.2.0"
view_pager_2 = "1.0.0"
webkit_version = "1.10.0"
security_crypto_version = "1.1.0-alpha06"
legacy_support_version = "1.0.0"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }

# Jetpack
legacy_support = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy_support_version" }
lifecycle_live_data_ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
lifecycle_view_model_ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
lifecycle_runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
ui = { group="androidx.compose.ui", name="ui", version.ref="compose_version" }
ui_graphics = { group="androidx.compose.ui", name="ui-graphics", version.ref="compose_version" }
ui_tooling = { group="androidx.compose.ui", name="ui-tooling", version.ref="compose_version" }
ui_tooling_preview = { group="androidx.compose.ui", name="ui-tooling-preview", version.ref="compose_version" }
material = { group="androidx.compose.material", name="material", version.ref="compose_material_version" }
material_icons_extended = { group="androidx.compose.material", name="material-icons-extended", version.ref="compose_material_version" }
ui_viewbinding = { group="androidx.compose.ui", name="ui-viewbinding", version.ref="compose_version" }
runtime = { group="androidx.compose.runtime", name="runtime", version.ref="compose_version" }
animation = { group="androidx.compose.animation", name="animation", version.ref="compose_version" }
activity_compose = { group="androidx.activity", name="activity-compose", version.ref="compose_version" }
compose_theme = { group="com.google.android.material", name="compose-theme-adapter", version.ref="compose_theme_version" }
constraintlayout_compose = { group="androidx.constraintlayout", name="constraintlayout-compose", version.ref="constraintlayout-compose-version" }
coil_compose = { group="io.coil-kt", name="coil-compose", version.ref="coil_version" }
coil = { group="io.coil-kt", name="coil", version.ref="coil_version" }
runtime_compose = { group="androidx.lifecycle", name="lifecycle-runtime-compose", version.ref="lifecycleVersion" }
viewmodel_compose = { group="androidx.lifecycle", name="lifecycle-viewmodel-compose", version.ref="lifecycleVersion" }
paging = { group="androidx.paging", name="paging-compose", version.ref="paging-version" }

# Accompanist
accompanist_pager = { group="com.google.accompanist", name="accompanist-pager", version.ref="accompanist_version" }
accompanist_pager_indicators = { group="com.google.accompanist", name="accompanist-pager-indicators", version.ref="accompanist_version" }
accompanist_swiperefresh = { group="com.google.accompanist", name="accompanist-swiperefresh", version.ref="accompanist_version" }
accompanist_systemuicontroller = { group="com.google.accompanist", name="accompanist-systemuicontroller", version.ref="accompanist_version" }
accompanist_flowlayout = { group="com.google.accompanist", name="accompanist-flowlayout", version.ref="accompanist_version" }
accompanist_webview = { group="com.google.accompanist", name="accompanist-webview", version.ref="accompanist_version" }

# NetworkDependencies
retrofit_core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
gson_converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
ok_http = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttpVersion" }
ok_http_interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttpVersion" }

# AndroidXDependencies
app_compat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material-design = { module = "com.google.android.material:material", version.ref = "material-design" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint-layout" }
lifecycle-ext = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-ext" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
nav_ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "nav_version" }
nav_fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "nav_version" }
view_pager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "view_pager_2" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit_version" }
security_crypto = { module = "androidx.security:security-crypto", version.ref = "security_crypto_version" }

# KoinDependencies
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koinVersion" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinVersion" }

# CxhuckerDependencies
chucker-library = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chuckerVersion" }
chucker-librarynoop = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chuckerVersion" }

# Kotlin
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines_version" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization_version" }

# Maps
google_maps_compose = { group="com.google.maps.android", name="maps-compose", version.ref="maps_compose_version" }
google_maps_compose_widgets = { group="com.google.maps.android", name="maps-compose-widgets", version.ref="maps_compose_version" }

# Unit-test
junit-junit = { module = "junit:junit", version.ref = "junit" }
junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

[bundles]
compose = [
    "ui",
    "ui_graphics",
    "ui_tooling",
    "ui_tooling_preview",
    "material",
    "ui_viewbinding",
    "runtime",
    "animation",
    "activity_compose",
    "compose_theme",
    "material_icons_extended",
    "constraintlayout_compose",
    "coil_compose",
    "coil",
    "runtime_compose",
    "viewmodel_compose",
]

accompanist = [
    "accompanist_pager",
    "accompanist_pager_indicators",
    "accompanist_swiperefresh",
    "accompanist_systemuicontroller",
    "accompanist_flowlayout",
    "accompanist_webview",
]

maps = [
    "google_maps_compose",
    "google_maps_compose_widgets",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains_kotlin_version" }
android-library = { id = "com.android.library", version.ref = "android-library" }
#navigation-safe-args-gradle-plugin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgsGradlePlugin" }